//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerraMystica.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Exceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Exceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TerraMystica.Resources.Exceptions", typeof(Exceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot afford..
        /// </summary>
        internal static string CannotAfford {
            get {
                return ResourceManager.GetString("CannotAfford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build on a tile that already has a building..
        /// </summary>
        internal static string CannotBuildExistingBuilding {
            get {
                return ResourceManager.GetString("CannotBuildExistingBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build on a tile that is not the home terrain..
        /// </summary>
        internal static string CannotBuildNotHomeTerrain {
            get {
                return ResourceManager.GetString("CannotBuildNotHomeTerrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot build on an owned tile..
        /// </summary>
        internal static string CannotBuildOwned {
            get {
                return ResourceManager.GetString("CannotBuildOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot not found on cult track..
        /// </summary>
        internal static string CannotCommitPriestSlotNotFound {
            get {
                return ResourceManager.GetString("CannotCommitPriestSlotNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot commit priest to an already used slot..
        /// </summary>
        internal static string CannotCommitPriestUsedSlot {
            get {
                return ResourceManager.GetString("CannotCommitPriestUsedSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot terraform an owned tile..
        /// </summary>
        internal static string CannotTerraformOwned {
            get {
                return ResourceManager.GetString("CannotTerraformOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot terraform to the same terrain type..
        /// </summary>
        internal static string CannotTerraformSameType {
            get {
                return ResourceManager.GetString("CannotTerraformSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Turn in scroll after player has passed..
        /// </summary>
        internal static string CannotTurnInScrollIfPassed {
            get {
                return ResourceManager.GetString("CannotTurnInScrollIfPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upgrade, building not found on board. .
        /// </summary>
        internal static string CannotUpgradeBuildingNotFound {
            get {
                return ResourceManager.GetString("CannotUpgradeBuildingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upgrade shipping distance beyond the maximum value..
        /// </summary>
        internal static string CannotUpgradeShippingPastMax {
            get {
                return ResourceManager.GetString("CannotUpgradeShippingPastMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot upgrade spade cost beyond the minimum value..
        /// </summary>
        internal static string CannotUpgradeSpadePastMin {
            get {
                return ResourceManager.GetString("CannotUpgradeSpadePastMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot terraform to void terrain type..
        /// </summary>
        internal static string InvalidVoidTerraform {
            get {
                return ResourceManager.GetString("InvalidVoidTerraform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power required exceeds power available. Requested {0}, Available {1}..
        /// </summary>
        internal static string NeedMorePower {
            get {
                return ResourceManager.GetString("NeedMorePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a positive number or zero..
        /// </summary>
        internal static string NegativeValueNotAllowed {
            get {
                return ResourceManager.GetString("NegativeValueNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile owned by another player..
        /// </summary>
        internal static string OwnedByOtherPlayer {
            get {
                return ResourceManager.GetString("OwnedByOtherPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Power in Bowl {0} cannot exceed the total power alloted {1}..
        /// </summary>
        internal static string PowerInBowlExceedsTotal {
            get {
                return ResourceManager.GetString("PowerInBowlExceedsTotal", resourceCulture);
            }
        }
    }
}
